version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.glassfish.jaxb:jaxb-runtime
    versions:
    - 3.0.0
  - dependency-name: jakarta.xml.bind:jakarta.xml.bind-api
    versions:
    - 3.0.0
  - dependency-name: org.junit.jupiter:junit-jupiter
    versions:
    - 5.7.0
